### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by orkhan10** [evemorgen/akttym#1]
wanted to ask whether this will be maintained further?

If yes, would like to report this error that i get after adding username, client_secret and client_secret.
 
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akttym/akttym.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(open(dir_path + '/config.yaml'))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akttym/__main__.py", line 11, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akttym/__main__.py", line 6, in main
    akttym()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akttym/akttym.py", line 25, in akttym
    check_config(config, dir_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akttym/akttym.py", line 12, in check_config
    if key not in config or config.get(key) is None:
AttributeError: 'str' object has no attribute 'get'

**Comment by evemorgen** [comment]
Thanks for reporting that @orkhan10, I'll look into that this week :)

**Comment by evemorgen** [comment]
@orkhan10 I did a major update to this library, feel free to install the newest version (`python3 -m pip install akttym==1.0.2`) and see if that helps (it forces newer version of `pyyaml` to be installed). If not, let me know and I'll drill into that further

**Comment by orkhan10** [comment]
Thanks a lot! Worked perfectly.
